// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateCoinAdapterModelWithToken
    {
        /// <summary>
        /// Initializes a new instance of the CreateCoinAdapterModelWithToken
        /// class.
        /// </summary>
        public CreateCoinAdapterModelWithToken()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateCoinAdapterModelWithToken
        /// class.
        /// </summary>
        public CreateCoinAdapterModelWithToken(string externalTokenAddress = default(string), string tokenName = default(string))
        {
            ExternalTokenAddress = externalTokenAddress;
            TokenName = tokenName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalTokenAddress")]
        public string ExternalTokenAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenName")]
        public string TokenName { get; set; }

    }
}
