// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EventResponse
    {
        /// <summary>
        /// Initializes a new instance of the EventResponse class.
        /// </summary>
        public EventResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventResponse class.
        /// </summary>
        public EventResponse(System.Guid? eventId = default(System.Guid?))
        {
            EventId = eventId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventId")]
        public System.Guid? EventId { get; set; }

    }
}
